/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Prikaz.java
 *
 * Created on Mar 27, 2010, 6:59:05 PM
 */

package paket;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author stevan
 */
public class Prikaz extends javax.swing.JFrame {

    /** Creates new form Prikaz */
    public Prikaz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tPoruka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lListaKljuceva = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        tKodiranaPoruka = new javax.swing.JTextField();
        dAutor = new javax.swing.JButton();
        dZatvori = new javax.swing.JButton();
        dKodiraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DES kodiranje");
        setResizable(false);

        jLabel1.setText("Poruka:");

        tPoruka.setColumns(64);
        tPoruka.setText("1110000011101100101111001100011101101100110110011010011000011101");

        jLabel2.setText("Kljucevi:");

        lListaKljuceva.setModel(new javax.swing.AbstractListModel() {
            Funkcije f = new Funkcije();
            Kljuc[] niz = f.vratiKljuceve();
            public int getSize() { return niz.length; }
            public Object getElementAt(int i) { return niz[i].getKljuc(); }
        });
        jScrollPane1.setViewportView(lListaKljuceva);

        jLabel3.setText("Kodirana poruka:");

        tKodiranaPoruka.setColumns(64);
        tKodiranaPoruka.setEditable(false);

        dAutor.setText("O autoru");
        dAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAutorActionPerformed(evt);
            }
        });

        dZatvori.setText("Zatvori");
        dZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dZatvoriActionPerformed(evt);
            }
        });

        dKodiraj.setText("Kodiraj");
        dKodiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKodirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(dAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dKodiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dZatvori))
                    .addComponent(tKodiranaPoruka, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPoruka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tKodiranaPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dAutor)
                    .addComponent(dZatvori)
                    .addComponent(dKodiraj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAutorActionPerformed
        JOptionPane.showMessageDialog(this, "Stevan Cvetkovic\ncvetkovic.stevan@gmail.com", "O autoru", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_dAutorActionPerformed

    private void dZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_dZatvoriActionPerformed

    private void dKodirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKodirajActionPerformed
        Funkcije f = new Funkcije();

        String por = this.tPoruka.getText();
        char[] cPor = por.toCharArray();
        int[] iPor = new int[64];

        for(int i=0; i<64; i++)
            iPor[i] = cPor[i] % 48;

        int[] cipher = f.obrada(iPor);
        String t = Arrays.toString(cipher).replace(", ", "").replace("[", "").replace("]", "");


        this.tKodiranaPoruka.setText(t);
    }//GEN-LAST:event_dKodirajActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prikaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dAutor;
    private javax.swing.JButton dKodiraj;
    private javax.swing.JButton dZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lListaKljuceva;
    private javax.swing.JTextField tKodiranaPoruka;
    private javax.swing.JTextField tPoruka;
    // End of variables declaration//GEN-END:variables

}
